file_type: csv
dataset_name: df
file_name: data
table_name: edsurv
inbound_delimiter: ","
outbound_delimiter: "|"
skip_leading_rows: 1
columns: 
    - text
    - source
    - text_length
    - prompt_id
    - word_count
